<?php
return array (
  38 => 
  array (
    'catid' => '38',
    'siteid' => '2',
    'type' => '1',
    'modelid' => '0',
    'parentid' => '0',
    'arrparentid' => '0',
    'child' => '1',
    'arrchildid' => '38,39,40,41,42,43',
    'catname' => 'PRODUCT SERVICE',
    'other_catname' => '',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => '',
    'catdir' => 'product_services',
    'url' => 'http://homestead.app/shituo/index.php?m=content&c=index&a=lists&catid=38',
    'items' => '0',
    'hits' => '0',
    'setting' => '{"ishtml":"0","template_list":"english","page_template":"page_product_services","meta_title":"","meta_keywords":"","meta_description":"","category_ruleid":"6","show_ruleid":"","repeatchargedays":"1"}',
    'listorder' => '38',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'product service',
    'usable_type' => '',
    'create_to_html_root' => NULL,
    'ishtml' => '0',
    'content_ishtml' => NULL,
    'category_ruleid' => '6',
    'show_ruleid' => '',
    'workflowid' => NULL,
    'isdomain' => '0',
  ),
  39 => 
  array (
    'catid' => '39',
    'siteid' => '2',
    'type' => '1',
    'modelid' => '0',
    'parentid' => '38',
    'arrparentid' => '0,38',
    'child' => '0',
    'arrchildid' => '39',
    'catname' => 'OUR ADVANTAGE',
    'other_catname' => '',
    'style' => '',
    'image' => '',
    'description' => 'To meet all the requirements of customers, one-stop service will make you more assured!',
    'parentdir' => 'product_services/',
    'catdir' => '',
    'url' => 'http://homestead.app/shituo/index.php?m=content&c=index&a=lists&catid=39',
    'items' => '0',
    'hits' => '0',
    'setting' => '{"ishtml":"0","template_list":"english","page_template":"page_product_services","meta_title":"","meta_keywords":"","meta_description":"","category_ruleid":"6","show_ruleid":"","repeatchargedays":"1"}',
    'listorder' => '39',
    'ismenu' => '0',
    'sethtml' => '0',
    'letter' => 'our advantage',
    'usable_type' => '',
    'create_to_html_root' => NULL,
    'ishtml' => '0',
    'content_ishtml' => NULL,
    'category_ruleid' => '6',
    'show_ruleid' => '',
    'workflowid' => NULL,
    'isdomain' => '0',
  ),
  40 => 
  array (
    'catid' => '40',
    'siteid' => '2',
    'type' => '1',
    'modelid' => '0',
    'parentid' => '38',
    'arrparentid' => '0,38',
    'child' => '0',
    'arrchildid' => '40',
    'catname' => '国际空运',
    'other_catname' => 'INTERNATIONAL AIR TRANSPORT',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => 'product_services/',
    'catdir' => '',
    'url' => 'http://homestead.app/shituo/index.php?m=content&c=index&a=lists&catid=40',
    'items' => '0',
    'hits' => '0',
    'setting' => '{"ishtml":"0","template_list":"english","page_template":"page_product_services","meta_title":"","meta_keywords":"","meta_description":"","category_ruleid":"6","show_ruleid":"","repeatchargedays":"1"}',
    'listorder' => '40',
    'ismenu' => '0',
    'sethtml' => '0',
    'letter' => 'guojikongyun',
    'usable_type' => '',
    'create_to_html_root' => NULL,
    'ishtml' => '0',
    'content_ishtml' => NULL,
    'category_ruleid' => '6',
    'show_ruleid' => '',
    'workflowid' => NULL,
    'isdomain' => '0',
  ),
  41 => 
  array (
    'catid' => '41',
    'siteid' => '2',
    'type' => '1',
    'modelid' => '0',
    'parentid' => '38',
    'arrparentid' => '0,38',
    'child' => '0',
    'arrchildid' => '41',
    'catname' => ' 国际海运',
    'other_catname' => 'INTERNATIONAL OCEAN SHIPPING',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => 'product_services/',
    'catdir' => '',
    'url' => 'http://homestead.app/shituo/index.php?m=content&c=index&a=lists&catid=41',
    'items' => '0',
    'hits' => '0',
    'setting' => '{"ishtml":"0","template_list":"english","page_template":"page_product_services","meta_title":"","meta_keywords":"","meta_description":"","category_ruleid":"6","show_ruleid":"","repeatchargedays":"1"}',
    'listorder' => '41',
    'ismenu' => '0',
    'sethtml' => '0',
    'letter' => ' guojihaiyun',
    'usable_type' => '',
    'create_to_html_root' => NULL,
    'ishtml' => '0',
    'content_ishtml' => NULL,
    'category_ruleid' => '6',
    'show_ruleid' => '',
    'workflowid' => NULL,
    'isdomain' => '0',
  ),
  42 => 
  array (
    'catid' => '42',
    'siteid' => '2',
    'type' => '1',
    'modelid' => '0',
    'parentid' => '38',
    'arrparentid' => '0,38',
    'child' => '0',
    'arrchildid' => '42',
    'catname' => 'Rights to enjoy',
    'other_catname' => '',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => 'product_services/',
    'catdir' => '',
    'url' => 'http://homestead.app/shituo/index.php?m=content&c=index&a=lists&catid=42',
    'items' => '0',
    'hits' => '0',
    'setting' => '{"ishtml":"0","template_list":"english","page_template":"page_product_services","meta_title":"","meta_keywords":"","meta_description":"","category_ruleid":"6","show_ruleid":"","repeatchargedays":"1"}',
    'listorder' => '42',
    'ismenu' => '0',
    'sethtml' => '0',
    'letter' => 'rights to enjoy',
    'usable_type' => '',
    'create_to_html_root' => NULL,
    'ishtml' => '0',
    'content_ishtml' => NULL,
    'category_ruleid' => '6',
    'show_ruleid' => '',
    'workflowid' => NULL,
    'isdomain' => '0',
  ),
  43 => 
  array (
    'catid' => '43',
    'siteid' => '2',
    'type' => '1',
    'modelid' => '0',
    'parentid' => '38',
    'arrparentid' => '0,38',
    'child' => '0',
    'arrchildid' => '43',
    'catname' => 'provide material',
    'other_catname' => '',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => 'product_services/',
    'catdir' => '',
    'url' => 'http://homestead.app/shituo/index.php?m=content&c=index&a=lists&catid=43',
    'items' => '0',
    'hits' => '0',
    'setting' => '{"ishtml":"0","template_list":"english","page_template":"page_product_services","meta_title":"","meta_keywords":"","meta_description":"","category_ruleid":"6","show_ruleid":"","repeatchargedays":"1"}',
    'listorder' => '43',
    'ismenu' => '0',
    'sethtml' => '0',
    'letter' => 'provide material',
    'usable_type' => '',
    'create_to_html_root' => NULL,
    'ishtml' => '0',
    'content_ishtml' => NULL,
    'category_ruleid' => '6',
    'show_ruleid' => '',
    'workflowid' => NULL,
    'isdomain' => '0',
  ),
  44 => 
  array (
    'catid' => '44',
    'siteid' => '2',
    'type' => '0',
    'modelid' => '14',
    'parentid' => '0',
    'arrparentid' => '0',
    'child' => '0',
    'arrchildid' => '44',
    'catname' => 'NEW CENTER',
    'other_catname' => '',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => '',
    'catdir' => '',
    'url' => 'http://homestead.app/shituo/index.php?m=content&c=index&a=lists&catid=44',
    'items' => '0',
    'hits' => '0',
    'setting' => '{"workflowid":"","ishtml":"0","content_ishtml":"0","create_to_html_root":"0","template_list":"english","category_template":"category","list_template":"list","show_template":"show","meta_title":"","meta_keywords":"","meta_description":"","presentpoint":"1","defaultchargepoint":"0","paytype":"0","repeatchargedays":"1","category_ruleid":"6","show_ruleid":"16"}',
    'listorder' => '44',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'new center',
    'usable_type' => '',
    'create_to_html_root' => '0',
    'ishtml' => '0',
    'content_ishtml' => '0',
    'category_ruleid' => '6',
    'show_ruleid' => '16',
    'workflowid' => '',
    'isdomain' => '0',
  ),
);
?>